#!/bin/bash

#BSUB -J PAPG21_MiSIGDB
#BSUB -P "acc_EHR_ML"
#BSUB -q premium 
#BSUB -n 6 
#BSUB -R span[hosts=1]
#BSUB -W 12:00 
#BSUB -o %J.stdout 
#BSUB -eo %J.stderr 
#BSUB -oo MiSIGDB_%J.out

sh plot_DIAG_T2D_MAGIC_UKBB_UACR_c7all_MiSIGDB.sh  
