#!/binsh


module load R
module load plink
module load plink2

Rscript PRSice.R --dir . --prsice PRSice_linux --base MAGIC1000G_FG_SAS.nodup.QC.txt --target PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.final --no-default --chr chromosome --A1 effect_allele --A2 other_allele --snp variant --pvalue p_value --bp base_pair_location --beta --cov PAPG21-3_capstone1000G_merged.QC.COV.final  --pheno PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.pheno.final --pheno-col T2D --ignore-fid --missing CENTER --thread 2  --stat beta  --gtf misigD_genesets/Homo_sapiens.GRCh37.87.gtf --binary-target T  --msigdb misigD_genesets/c7.all.v7.4.symbols.gmt --multi-plot 10  --out MAGIC_FG_PRSet_PAPG21-3_1000gSAS_GRCh37.c7ALLv74

Rscript PRSice.R --dir . --prsice PRSice_linux --base METAANALYSIS_DIAGRAM_SE1.BMI.MOD.nodup.QC.txt --extract DIAGRAM2017_META_PRSice_avg_PAPG21-3_1000gSAS_GRCh37.valid --target PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.final --no-default --chr CHR --A1 Allele1 --A2 Allele2 --snp SNP --chr-id c:l --pvalue P-value --bp BP --beta --cov PAPG21-3_capstone1000G_merged.QC.COV.final  --pheno PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.pheno.final --pheno-col T2D --ignore-fid --missing CENTER --thread 2  --stat Effect  --gtf misigD_genesets/Homo_sapiens.GRCh37.87.gtf --binary-target T  --msigdb misigD_genesets/c7.all.v7.4.symbols.gmt --multi-plot 10  --out DIAGRAM_SE1_PRSet_PAPG21-3_1000gSAS_GRCh37.c7ALLv74

Rscript PRSice.R --dir . --prsice PRSice_linux --base T2D_TranEthnic.BMIadjusted.nodup.QC.final.txt --extract T2D_TE_PRSice_avg_PAPG21-3_1000gSAS_GRCh37.valid --target PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.final --no-default --chr CHR --A1 A1 --A2 A2 --snp SNP --chr-id c:l --pvalue P --bp BP --beta --cov PAPG21-3_capstone1000G_merged.QC.COV.final  --pheno PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.pheno.final --pheno-col T2D --ignore-fid --missing CENTER --thread 2  --stat BETA  --gtf misigD_genesets/Homo_sapiens.GRCh37.87.gtf --binary-target T  --msigdb misigD_genesets/c7.all.v7.4.symbols.gmt --multi-plot 10  --out T2D_TranEthnic_PRSet_PAPG21-3_1000gSAS_GRCh37.c7ALLv74

Rscript PRSice.R --dir . --prsice PRSice_linux --base UKBB.GWAS1KG.EXOME.CAD.SOFT.META.PublicRelease.300517.nodup.QC.txt --target PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.final --no-default --chr chr --A1 effect_allele --A2 noneffect_allele --snp snptestid --pvalue p-value_gc --bp bp_hg19 --or --cov PAPG21-3_capstone1000G_merged.QC.COV.final  --pheno PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.pheno.final --pheno-col T2D --ignore-fid --missing CENTER --thread 2  --stat logOR  --gtf misigD_genesets/Homo_sapiens.GRCh37.87.gtf --binary-target T  --msigdb misigD_genesets/c7.all.v7.4.symbols.gmt --multi-plot 10  --out UKBB_CAD_PRSet_PAPG21-3_1000gSAS_GRCh37.c7ALLv74

Rscript PRSice.R --dir . --prsice PRSice_linux --base UACR_formatted_20170020_DM-All-nstud_18-SumMac_400.tbl.ALLrsid.nodup.QC.txt --target PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.final --no-default --chr Chr --A1 Allele1 --A2 Allele2 --snp RSID --pvalue P-value --bp Pos_b37 --beta --cov PAPG21-3_capstone1000G_merged.QC.COV.final  --pheno PAPG21-3_capstone_1000g_allphase3SAS_GRCh37.QC-merged_excludemissnp.pheno.final --pheno-col T2D --ignore-fid --missing CENTER --thread 2  --stat Effect  --gtf misigD_genesets/Homo_sapiens.GRCh37.87.gtf --binary-target T  --msigdb misigD_genesets/c7.all.v7.4.symbols.gmt --multi-plot 10  --out UACR_DM_PRSet_PAPG21-3_1000gSAS_GRCh37.c7ALLv74
